datasource-host: mysql5_7
datasource-port: 3306
datasource-username: root
datasource-password: wc123456
datasource-db: balance-test
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${datasource-host}:${datasource-port}/${datasource-db}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${datasource-username}
    password: ${datasource-password}
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: debug
    reactor:
      netty: info
    javax.management.remote.rmi: info
    _org.springframework.web.servlet.HandlerMapping.Mappings: off
    net.sf.ehcache: info
    io.netty: info
    io.netty.handler.logging.LoggingHandler: debug
    org.apache: info
    org.hibernate: info
    com.alibaba.druid.pool.PreparedStatementPool: info
    org.springframework.orm.jpa.JpaTransactionManager: info
    com.zaxxer.hikari: info
    sun.rmi: info
    org:
      mybatis:
        spring:
          mapper:
            ClassPathMapperScanner: info
      hibernate:
        validator:
          internal:
            engine: info
      springframework: info
      springframework.context.support.PostProcessorRegistrationDelegate: warn

  pattern:
    console: "%white(%d{yyyyMMdd HHmmss}) %clr(%-5level) %white(%10.10thread) %white(%30.30logger{30}) %clr(%msg%n){magenta}"

mybatis-plus:
  global-config:
    banner: off
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8096
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
